// =========================================================
// Kurikulum "Dunia Ajaib Awan" — kelas desain untuk anak.
// 8 pertemuan. Pertemuan 1 lengkap; sisanya kerangka siap diisi.
//
// Cara menambah materi: tinggal isi `langkah`, `kuis`, dan
// `aktivitas` pada pertemuan berikutnya dengan pola yang sama.
// =========================================================

export const pertemuan = [
  {
    id: 1,
    judul: 'Dunia Warna',
    emoji: '🌈',
    tag: 'Mengenal warna',
    warna: '#7ec8f3',
    lencana: { ikon: '🎨', nama: 'Ahli Warna' },

    // Langkah belajar (slide). Tipe: 'teks' atau 'warna' (pakai contoh warna).
    langkah: [
      {
        tipe: 'teks',
        mood: 'semangat',
        judul: 'Halo, Sahabat Desainer!',
        teks: 'Aku <strong>Awan</strong>! Hari ini kita masuk ke <strong>Dunia Warna</strong>. Di dunia desain, warna itu seperti <strong>sihir</strong> — bisa membuat gambar jadi hidup dan punya perasaan. Yuk mulai! 💫',
      },
      {
        tipe: 'warna',
        mood: 'senang',
        judul: '3 Warna Utama',
        teks: 'Ada 3 warna <strong>utama</strong> (disebut warna primer): <strong>Merah, Kuning, dan Biru</strong>. Dari tiga warna ajaib ini, kita bisa membuat hampir semua warna lain!',
        contoh: [
          { warna: '#ff5a5a', nama: 'Merah' },
          { warna: '#ffd93b', nama: 'Kuning' },
          { warna: '#4a9fd6', nama: 'Biru' },
        ],
      },
      {
        tipe: 'campur',
        mood: 'mikir',
        judul: 'Mencampur Warna',
        teks: 'Kalau dua warna utama dicampur, lahir warna baru! Coba lihat keajaibannya:',
        campuran: [
          { a: '#4a9fd6', b: '#ffd93b', hasil: '#5fcf80', nama: 'Hijau' },
          { a: '#ff5a5a', b: '#ffd93b', hasil: '#ff9f43', nama: 'Oranye' },
          { a: '#ff5a5a', b: '#4a9fd6', hasil: '#a96fd0', nama: 'Ungu' },
        ],
      },
      {
        tipe: 'warna',
        mood: 'senang',
        judul: 'Warna Hangat & Sejuk',
        teks: 'Warna <strong>hangat</strong> (merah, oranye, kuning) terasa seperti <strong>matahari & api</strong> ☀️. Warna <strong>sejuk</strong> (biru, hijau, ungu) terasa seperti <strong>air & es</strong> 🧊.',
        contoh: [
          { warna: '#ff7043', nama: 'Hangat' },
          { warna: '#ffb74d', nama: 'Hangat' },
          { warna: '#4fc3f7', nama: 'Sejuk' },
          { warna: '#81c784', nama: 'Sejuk' },
        ],
      },
      {
        tipe: 'teks',
        mood: 'bangga',
        judul: 'Warna Punya Perasaan',
        teks: 'Hebatnya, warna bisa membuat kita <strong>merasa</strong> sesuatu! Kuning bikin <strong>ceria</strong> 😄, biru bikin <strong>tenang</strong> 😌, merah bikin <strong>bersemangat</strong> 🔥. Desainer memilih warna sesuai perasaan yang ingin disampaikan.',
      },
    ],

    // Kuis pilihan ganda. `benar` = indeks jawaban benar.
    kuis: [
      { soal: 'Kamu mau menggambar matahari yang ceria. Warna apa yang paling cocok?',
        pilihan: ['Biru', 'Kuning', 'Abu-abu', 'Ungu'], benar: 1,
        penjelasan: 'Kuning itu warna hangat yang membuat ceria, seperti matahari.' },
      { soal: 'Catmu habis warna hijau. Dua warna apa yang bisa dicampur untuk membuatnya?',
        pilihan: ['Merah + Biru', 'Biru + Kuning', 'Merah + Kuning', 'Putih + Hitam'], benar: 1,
        penjelasan: 'Biru + Kuning = Hijau. Itulah hebatnya warna primer!' },
      { soal: 'Untuk menggambar suasana malam yang tenang, warna apa yang paling pas?',
        pilihan: ['Merah', 'Oranye', 'Biru tua', 'Kuning'], benar: 2,
        penjelasan: 'Biru termasuk warna sejuk yang memberi rasa tenang dan teduh.' },
      { soal: 'Kelompok mana yang SEMUANYA warna hangat?',
        pilihan: ['Merah, Oranye, Kuning', 'Biru, Hijau, Ungu', 'Hijau, Merah, Biru', 'Ungu, Kuning, Biru'], benar: 0,
        penjelasan: 'Merah, oranye, dan kuning terasa hangat seperti api dan matahari.' },
      { soal: 'Mana yang BUKAN warna utama (primer)?',
        pilihan: ['Merah', 'Hijau', 'Biru', 'Kuning'], benar: 1,
        penjelasan: 'Hijau adalah warna campuran (biru + kuning), bukan warna primer.' },
    ],

    // Aktivitas kreatif: mewarnai pemandangan.
    aktivitas: {
      tipe: 'mewarnai',
      judul: 'Ayo Warnai Taman Awan!',
      petunjuk: 'Pilih warna di atas, lalu ketuk bagian gambar untuk mewarnainya. 🖌️',
      palet: ['#4fc3f7', '#5fcf80', '#ffd93b', '#ff7aa8', '#ff9f43', '#a96fd0', '#ffffff', '#7a5230'],
    },
  },

  {
    id: 2,
    judul: 'Dunia Bentuk',
    emoji: '🔷',
    tag: 'Bentuk dasar',
    warna: '#ffb6d5',
    lencana: { ikon: '⭐', nama: 'Penjelajah Bentuk' },

    langkah: [
      {
        tipe: 'teks',
        mood: 'semangat',
        judul: 'Masuk ke Dunia Bentuk!',
        teks: 'Tahukah kamu? <strong>Semua gambar</strong> tersusun dari bentuk-bentuk sederhana. Kalau kita tahu bentuk dasar, kita bisa menggambar <strong>apa saja</strong>! Yuk berkenalan dengan mereka. 🔷',
      },
      {
        tipe: 'bentuk',
        mood: 'senang',
        judul: 'Bentuk Dasar',
        teks: 'Ini tiga bentuk paling sering dipakai. Coba sebutkan namanya bersama Awan!',
        bentuk: [
          { bentuk: 'lingkaran', warna: '#4fc3f7', nama: 'Lingkaran' },
          { bentuk: 'persegi', warna: '#5fcf80', nama: 'Persegi' },
          { bentuk: 'segitiga', warna: '#ffb74d', nama: 'Segitiga' },
        ],
      },
      {
        tipe: 'teks',
        mood: 'mikir',
        judul: 'Bentuk Ada di Mana-mana',
        teks: 'Coba lihat sekelilingmu! 🎡 Roda itu <strong>lingkaran</strong>, jendela itu <strong>persegi</strong>, dan atap rumah itu <strong>segitiga</strong>. Bentuk bersembunyi di banyak benda!',
      },
      {
        tipe: 'bentuk',
        mood: 'semangat',
        judul: 'Menggabungkan Bentuk',
        teks: 'Sihir desain: gabungkan bentuk jadi gambar baru! <strong>Segitiga + persegi = rumah</strong> 🏠. Bentuk-bentuk kecil bekerja sama.',
        ilustrasi: 'rumah',
      },
      {
        tipe: 'teks',
        mood: 'bangga',
        judul: 'Kamu Hampir Jago!',
        teks: 'Sekarang kamu tahu rahasianya: untuk menggambar sesuatu yang sulit, pecah dulu jadi <strong>bentuk-bentuk sederhana</strong>. Ayo buktikan di kuis & gambar! ✨',
      },
    ],

    kuis: [
      { soal: 'Untuk menggambar rumah sederhana, dua bentuk apa yang kamu gabungkan?',
        pilihan: ['Persegi + Segitiga', 'Lingkaran + Lingkaran', 'Segitiga + Segitiga', 'Persegi + Persegi'], benar: 0,
        penjelasan: 'Persegi jadi badan rumah, segitiga jadi atapnya.' },
      { soal: 'Bentuk apa yang punya 3 sisi dan 3 sudut?',
        pilihan: ['Persegi', 'Lingkaran', 'Segitiga', 'Persegi panjang'], benar: 2,
        penjelasan: 'Segitiga selalu punya 3 sisi dan 3 sudut.' },
      { soal: 'Roda sepeda dan bola pantai sama-sama berbentuk...',
        pilihan: ['Segitiga', 'Lingkaran', 'Persegi', 'Bintang'], benar: 1,
        penjelasan: 'Keduanya bulat tanpa sudut, yaitu lingkaran.' },
      { soal: 'Kamu mau menggambar jendela yang kotak. Bentuk apa yang dipakai?',
        pilihan: ['Lingkaran', 'Segitiga', 'Persegi', 'Garis lengkung'], benar: 2,
        penjelasan: 'Jendela kotak paling pas digambar dengan persegi.' },
      { soal: 'Kenapa desainer suka memecah gambar jadi bentuk-bentuk sederhana?',
        pilihan: ['Supaya lebih sulit', 'Supaya lebih mudah digambar', 'Supaya tidak berwarna', 'Supaya lama selesai'], benar: 1,
        penjelasan: 'Memecah jadi bentuk sederhana membuat gambar rumit jadi lebih mudah.' },
    ],

    aktivitas: {
      tipe: 'menggambar',
      judul: 'Gambar Rumah Impianmu! 🏠',
      petunjuk: 'Pakai persegi, segitiga, dan lingkaran untuk menggambar rumah, pohon, atau apa pun yang kamu suka. Pilih warna & ukuran kuas, lalu coret di kanvas!',
      palet: ['#4fc3f7', '#5fcf80', '#ffd93b', '#ff7aa8', '#ff9f43', '#a96fd0', '#4a4a6a', '#ffffff'],
    },
  },
  {
    id: 3,
    judul: 'Dunia Garis',
    emoji: '✏️',
    tag: 'Garis & goresan',
    warna: '#b8f0d8',
    lencana: { ikon: '✏️', nama: 'Tukang Garis' },
    langkah: [
      { tipe: 'teks', mood: 'semangat', judul: 'Selamat Datang di Dunia Garis!',
        teks: 'Setiap gambar dimulai dari sebuah <strong>garis</strong>. Garis adalah jejak yang ditinggalkan pensilmu saat berjalan. Yuk kenali macam-macam garis! ✏️' },
      { tipe: 'garis', mood: 'senang', judul: 'Macam-Macam Garis',
        teks: 'Ada garis <strong>lurus</strong>, <strong>lengkung</strong>, dan <strong>zigzag</strong>. Masing-masing punya rasa berbeda!',
        garis: [
          { garis: 'lurus', warna: '#4a9fd6', nama: 'Lurus' },
          { garis: 'lengkung', warna: '#5fcf80', nama: 'Lengkung' },
          { garis: 'zigzag', warna: '#ff9f43', nama: 'Zigzag' },
        ] },
      { tipe: 'garis', mood: 'mikir', judul: 'Garis Punya Perasaan',
        teks: 'Garis <strong>lurus</strong> terasa tenang & kuat. Garis <strong>lengkung</strong> terasa lembut & ceria. Garis <strong>zigzag</strong> terasa seru & bersemangat!',
        garis: [
          { garis: 'tebal', warna: '#a96fd0', nama: 'Tebal = berani' },
          { garis: 'putus', warna: '#7ec8f3', nama: 'Putus-putus = lembut' },
        ] },
      { tipe: 'teks', mood: 'bangga', judul: 'Garis Membangun Gambar',
        teks: 'Gabungkan banyak garis, jadilah gambar! Rambut keriting dari garis lengkung, gunung dari garis zigzag, pagar dari garis lurus. Sekarang giliranmu bereksperimen! 🌟' },
    ],
    kuis: [
      { soal: 'Untuk menggambar ombak laut yang tenang, garis apa yang paling cocok?',
        pilihan: ['Lurus', 'Zigzag', 'Lengkung', 'Putus-putus'], benar: 2,
        penjelasan: 'Garis lengkung mengalir lembut, pas untuk ombak.' },
      { soal: 'Petir menyambar di langit badai. Garis apa yang paling menggambarkannya?',
        pilihan: ['Lengkung', 'Zigzag', 'Lurus', 'Lingkaran'], benar: 1,
        penjelasan: 'Zigzag yang tajam terasa cepat dan bersemangat, seperti petir.' },
      { soal: 'Pagar kayu yang berdiri tegak paling pas digambar dengan garis...',
        pilihan: ['Lurus', 'Lengkung', 'Zigzag', 'Spiral'], benar: 0,
        penjelasan: 'Garis lurus terasa tenang, kuat, dan rapi seperti pagar.' },
      { soal: 'Rambut yang keriting paling cocok digambar dengan garis...',
        pilihan: ['Lurus', 'Lengkung', 'Putus-putus', 'Tebal lurus'], benar: 1,
        penjelasan: 'Garis lengkung yang berputar membuat kesan keriting.' },
      { soal: 'Garis yang tebal memberi kesan...',
        pilihan: ['Lemah dan kecil', 'Kuat dan berani', 'Sedih', 'Dingin'], benar: 1,
        penjelasan: 'Makin tebal garisnya, makin kuat dan berani kesannya.' },
    ],
    aktivitas: { tipe: 'menggambar', judul: 'Bermain dengan Garis! ✏️',
      petunjuk: 'Coba gambar pakai bermacam garis: lurus, lengkung, dan zigzag. Buat ombak, gunung, atau apa pun yang kamu mau!',
      palet: ['#4a9fd6', '#5fcf80', '#ff9f43', '#a96fd0', '#ff7aa8', '#4a4a6a', '#ffd93b', '#ffffff'] },
  },

  {
    id: 4,
    judul: 'Dunia Pola',
    emoji: '🌸',
    tag: 'Pola & motif',
    warna: '#ffe39b',
    lencana: { ikon: '🌸', nama: 'Pencipta Pola' },
    langkah: [
      { tipe: 'teks', mood: 'semangat', judul: 'Masuk ke Dunia Pola!',
        teks: 'Pola adalah gambar yang <strong>berulang</strong> lagi dan lagi. Pola ada di baju, selimut, ubin, dan banyak benda. Pola membuat sesuatu terlihat rapi dan cantik! 🌸' },
      { tipe: 'pola', mood: 'senang', judul: 'Contoh Pola',
        teks: 'Lihat, motif kecil yang diulang membentuk pola yang indah:',
        pola: [
          { pola: 'titik', warna: '#ff7aa8', nama: 'Titik' },
          { pola: 'garis', warna: '#7ec8f3', nama: 'Garis' },
          { pola: 'bunga', warna: '#ff9f43', warna2: '#ffe39b', nama: 'Bunga' },
        ] },
      { tipe: 'pola', mood: 'mikir', judul: 'Pola dari Apa Saja',
        teks: 'Kamu bisa membuat pola dari bentuk apa pun — bahkan dari <strong>hati</strong>! Rahasianya: ulangi dengan jarak yang sama. 💕',
        pola: [
          { pola: 'hati', warna: '#ff7aa8', warna2: '#ffb6d5', nama: 'Hati' },
        ] },
      { tipe: 'teks', mood: 'bangga', judul: 'Kamu Pencipta Pola!',
        teks: 'Pilih satu motif kesukaanmu, lalu ulangi. Itulah cara desainer membuat motif baju dan kertas kado. Ayo coba buat polamu sendiri! ✨' },
    ],
    kuis: [
      { soal: 'Apa ciri utama sebuah pola?',
        pilihan: ['Motif yang berulang teratur', 'Gambar yang acak', 'Hanya satu warna', 'Sekali gambar saja'], benar: 0,
        penjelasan: 'Pola adalah motif yang diulang-ulang dengan teratur.' },
      { soal: 'Kamu mengulang gambar hati berjajar rapi di kertas. Kamu sedang membuat...',
        pilihan: ['Karakter', 'Latar', 'Pola', 'Cerita'], benar: 2,
        penjelasan: 'Mengulang motif secara teratur berarti membuat pola.' },
      { soal: 'Supaya pola terlihat rapi dan enak dilihat, jarak antar motif sebaiknya...',
        pilihan: ['Acak-acakan', 'Sama dan teratur', 'Makin lama makin jauh', 'Saling menumpuk'], benar: 1,
        penjelasan: 'Jarak yang sama membuat pola terlihat rapi.' },
      { soal: 'Benda mana yang paling sering punya pola?',
        pilihan: ['Air sungai', 'Kain batik', 'Batu kerikil', 'Awan'], benar: 1,
        penjelasan: 'Kain batik penuh motif berulang yang indah.' },
    ],
    aktivitas: { tipe: 'menggambar', judul: 'Buat Polamu Sendiri! 🌸',
      petunjuk: 'Pilih satu bentuk kecil (titik, bunga, atau hati), lalu ulangi di seluruh kanvas. Jadikan pola kertas kado yang cantik!',
      palet: ['#ff7aa8', '#ffb6d5', '#7ec8f3', '#5fcf80', '#ff9f43', '#ffd93b', '#a96fd0', '#ffffff'] },
  },

  {
    id: 5,
    judul: 'Dunia Karakter',
    emoji: '🐶',
    tag: 'Membuat tokoh',
    warna: '#d3b8f5',
    lencana: { ikon: '🐶', nama: 'Perancang Karakter' },
    langkah: [
      { tipe: 'teks', mood: 'semangat', judul: 'Ayo Buat Karakter!',
        teks: 'Karakter adalah <strong>tokoh</strong> dalam gambar kita — bisa hewan, manusia, atau makhluk ajaib. Kabar baiknya: karakter juga dibuat dari <strong>bentuk sederhana</strong>! 🐶' },
      { tipe: 'bentuk', mood: 'senang', judul: 'Mulai dari Bentuk',
        teks: 'Wajah bulat dari <strong>lingkaran</strong>, telinga dari <strong>segitiga</strong>. Gabungkan, jadilah kepala karakter!',
        bentuk: [
          { bentuk: 'lingkaran', warna: '#ffd1a8', nama: 'Wajah' },
          { bentuk: 'segitiga', warna: '#ff9fb6', nama: 'Telinga' },
        ] },
      { tipe: 'teks', mood: 'mikir', judul: 'Mata Membuatnya Hidup',
        teks: 'Rahasia karakter lucu ada di <strong>mata besar</strong> dan <strong>pipi merona</strong>! Senyum kecil bikin karakter terlihat ramah. 😊',
        ilustrasi: 'karakter' },
      { tipe: 'teks', mood: 'bangga', judul: 'Karaktermu, Aturanmu!',
        teks: 'Karakter buatanmu bebas berwarna apa saja — kucing ungu, anjing biru, semua boleh! Yuk wujudkan karakter impianmu. 🌈' },
    ],
    kuis: [
      { soal: 'Saat membuat karakter, bentuk apa yang biasanya digambar lebih dulu untuk wajahnya?',
        pilihan: ['Lingkaran', 'Zigzag', 'Garis lurus', 'Persegi panjang'], benar: 0,
        penjelasan: 'Wajah biasanya dimulai dari lingkaran, lalu ditambah bagian lain.' },
      { soal: 'Telinga kucing yang runcing paling cocok dibuat dari bentuk...',
        pilihan: ['Lingkaran', 'Segitiga', 'Persegi', 'Garis lengkung'], benar: 1,
        penjelasan: 'Segitiga membuat telinga terlihat runcing seperti kucing.' },
      { soal: 'Apa yang paling membuat sebuah karakter terlihat lucu dan hidup?',
        pilihan: ['Mata besar dan senyum', 'Tanpa wajah', 'Warna abu-abu polos', 'Garis yang kaku'], benar: 0,
        penjelasan: 'Mata besar dan senyum kecil membuat karakter terasa ramah dan hidup.' },
      { soal: 'Bolehkah karaktermu berwarna ungu atau biru?',
        pilihan: ['Tidak boleh', 'Boleh, sesuai imajinasimu', 'Hanya boleh hitam', 'Harus warna asli'], benar: 1,
        penjelasan: 'Dalam desain, karaktermu bebas berwarna apa saja sesuai imajinasi.' },
    ],
    aktivitas: { tipe: 'mewarnai', scene: 'karakter', judul: 'Warnai Si Burung Hantu! 🦉',
      petunjuk: 'Beri warna pada karakter burung hantu ini sesukamu. Pilih warna lalu ketuk bagian gambar!',
      palet: ['#ffb74d', '#a96fd0', '#7ec8f3', '#5fcf80', '#ff7aa8', '#ffd93b', '#b07a4f', '#ffffff'] },
  },

  {
    id: 6,
    judul: 'Dunia Latar',
    emoji: '🏰',
    tag: 'Latar & suasana',
    warna: '#9fd8ef',
    lencana: { ikon: '🏰', nama: 'Pembangun Dunia' },
    langkah: [
      { tipe: 'teks', mood: 'semangat', judul: 'Bangun Dunia di Belakang!',
        teks: 'Latar adalah <strong>pemandangan di belakang</strong> karakter — langit, gunung, rumah, atau kastil. Latar memberi tahu kita: cerita ini terjadi di mana? 🏰' },
      { tipe: 'teks', mood: 'senang', judul: 'Jauh & Dekat',
        teks: 'Benda yang <strong>jauh</strong> digambar kecil di atas; yang <strong>dekat</strong> digambar besar di bawah. Itulah cara membuat gambar terasa luas!',
        ilustrasi: 'pemandangan' },
      { tipe: 'warna', mood: 'mikir', judul: 'Warna Menentukan Suasana',
        teks: 'Latar <strong>biru muda</strong> = siang cerah ☀️. Latar <strong>ungu gelap</strong> = malam misterius 🌙. Warna latar membuat perasaan cerita!',
        contoh: [
          { warna: '#bfe9ff', nama: 'Siang' },
          { warna: '#ffd6a8', nama: 'Senja' },
          { warna: '#5b4b8a', nama: 'Malam' },
        ] },
      { tipe: 'teks', mood: 'bangga', judul: 'Dunia Ajaibmu',
        teks: 'Sekarang kamu bisa membangun dunia untuk karaktermu! Mau kastil di awan, atau rumah di hutan? Kamu yang menentukan! ✨' },
    ],
    kuis: [
      { soal: 'Apa gunanya latar (background) dalam sebuah gambar?',
        pilihan: ['Menunjukkan di mana cerita terjadi', 'Tidak ada gunanya', 'Membuat gambar kosong', 'Menghapus karakter'], benar: 0,
        penjelasan: 'Latar memberi tahu tempat dan suasana cerita.' },
      { soal: 'Ada gunung yang jauh dan bunga yang dekat. Mana yang digambar lebih besar?',
        pilihan: ['Gunung', 'Bunga yang dekat', 'Sama besar', 'Keduanya kecil'], benar: 1,
        penjelasan: 'Benda yang dekat digambar besar, yang jauh digambar kecil.' },
      { soal: 'Kamu ingin membuat suasana malam yang misterius. Warna latar apa yang cocok?',
        pilihan: ['Kuning cerah', 'Biru atau ungu gelap', 'Putih', 'Oranye terang'], benar: 1,
        penjelasan: 'Warna gelap seperti biru tua dan ungu memberi kesan malam.' },
      { soal: 'Benda yang letaknya jauh sebaiknya digambar...',
        pilihan: ['Besar di bawah', 'Kecil di bagian atas', 'Sangat besar', 'Menutupi karakter'], benar: 1,
        penjelasan: 'Benda jauh terlihat kecil dan biasanya di bagian atas gambar.' },
    ],
    aktivitas: { tipe: 'mewarnai', scene: 'kastil', judul: 'Warnai Kastil Ajaib! 🏰',
      petunjuk: 'Beri warna pada kastil dan langitnya. Mau suasana siang atau malam? Kamu yang pilih!',
      palet: ['#bfe9ff', '#5b4b8a', '#ff7aa8', '#ffd93b', '#a96fd0', '#5fcf80', '#b07a4f', '#ffffff'] },
  },

  {
    id: 7,
    judul: 'Dunia Cerita',
    emoji: '📖',
    tag: 'Bercerita lewat gambar',
    warna: '#ffc6a8',
    lencana: { ikon: '📖', nama: 'Pendongeng Gambar' },
    langkah: [
      { tipe: 'teks', mood: 'semangat', judul: 'Gambar Bisa Bercerita!',
        teks: 'Desainer hebat tidak cuma menggambar — mereka <strong>bercerita</strong>. Satu gambar bisa menyimpan sebuah kisah. 📖' },
      { tipe: 'teks', mood: 'senang', judul: 'Awal, Tengah, Akhir',
        teks: 'Setiap cerita punya 3 bagian: <strong>awal</strong> (mulai), <strong>tengah</strong> (kejadian), dan <strong>akhir</strong> (selesai). Lihat kisah biji tumbuh jadi bunga:',
        ilustrasi: 'cerita' },
      { tipe: 'teks', mood: 'mikir', judul: 'Gabungkan Semua Ilmumu',
        teks: 'Sekarang kamu punya semuanya: <strong>warna</strong>, <strong>bentuk</strong>, <strong>garis</strong>, <strong>karakter</strong>, dan <strong>latar</strong>. Gabungkan jadi satu gambar bercerita! 🎨' },
      { tipe: 'teks', mood: 'bangga', judul: 'Kamu Pendongeng!',
        teks: 'Pikirkan: siapa tokohnya? Di mana? Apa yang terjadi? Lalu gambarkan. Cerita sederhana pun bisa sangat berkesan. ✨' },
    ],
    kuis: [
      { soal: 'Sebuah cerita yang baik punya tiga bagian: awal, tengah, dan...',
        pilihan: ['Akhir', 'Warna', 'Garis', 'Pola'], benar: 0,
        penjelasan: 'Awal, tengah, dan akhir membuat cerita terasa utuh.' },
      { soal: 'Gambar "biji ditanam", lalu "tunas tumbuh", lalu "bunga mekar". Tiga gambar ini menunjukkan...',
        pilihan: ['Sebuah cerita', 'Sebuah pola', 'Sebuah warna', 'Sebuah bentuk'], benar: 0,
        penjelasan: 'Urutan kejadian dari awal ke akhir itu adalah cerita.' },
      { soal: 'Untuk membuat satu gambar yang bercerita, apa yang sebaiknya digabung?',
        pilihan: ['Karakter dan latar', 'Hanya satu titik', 'Tidak ada apa-apa', 'Hanya satu garis'], benar: 0,
        penjelasan: 'Karakter (tokoh) ditambah latar (tempat) membuat gambar bercerita.' },
      { soal: 'Bagian cerita yang menunjukkan "masalah selesai dan semua bahagia" adalah...',
        pilihan: ['Awal', 'Tengah', 'Akhir', 'Judul'], benar: 2,
        penjelasan: 'Bagian akhir adalah saat cerita selesai.' },
    ],
    aktivitas: { tipe: 'menggambar', judul: 'Gambar Ceritamu! 📖',
      petunjuk: 'Gambar satu adegan cerita: ada tokoh, ada latar, ada sesuatu yang terjadi. Ceritakan kisahmu lewat gambar!',
      palet: ['#7ec8f3', '#5fcf80', '#ffd93b', '#ff7aa8', '#ff9f43', '#a96fd0', '#4a4a6a', '#ffffff'] },
  },

  {
    id: 8,
    judul: 'Sihir Gambar AI',
    emoji: '🤖',
    tag: 'Membuat gambar & video dengan AI',
    warna: '#bcdcff',
    lencana: { ikon: '🤖', nama: 'Penyihir AI' },
    langkah: [
      { tipe: 'teks', mood: 'semangat', judul: 'Kenalan dengan AI',
        teks: 'AI itu seperti <strong>teman robot pintar</strong> yang bisa membantu membuat <strong>gambar</strong> dan bahkan <strong>video</strong> — cukup dari kata-kata yang kita berikan! Keren, kan? 🤖✨' },
      { tipe: 'teks', mood: 'senang', judul: 'Mantra Ajaib (Prompt)',
        teks: 'Cara bicara dengan AI disebut <strong>prompt</strong>, kita sebut saja <strong>mantra ajaib</strong>. Contohnya: <strong>"anak kucing oranye memakai topi pesta"</strong>. Makin jelas mantranya, makin bagus gambarnya! 🪄' },
      { tipe: 'teks', mood: 'mikir', judul: 'Resep Mantra yang Bagus',
        teks: 'Mantra hebat punya 4 bahan: <strong>SIAPA</strong> + <strong>SEDANG APA</strong> + <strong>DI MANA</strong> + <strong>GAYA/WARNA</strong>. Contoh: "naga kecil biru 🐉 terbang di kota awan ☁️, gaya kartun lucu".' },
      { tipe: 'teks', mood: 'semangat', judul: 'AI Juga Bisa Membuat Video!',
        teks: 'Mau gambarmu <strong>bergerak</strong>? Tambahkan kata <strong>gerakan</strong>: "lalu melompat-lompat" atau "kamera bergerak pelan". AI akan mengubah gambar jadi video singkat! 🎬' },
      { tipe: 'teks', mood: 'mikir', judul: 'Selalu Ditemani Orang Dewasa 💛',
        teks: 'Penting! Buka alat AI <strong>bersama Mama atau Papa</strong>. Jangan beri tahu nama lengkap, sekolah, atau alamat ke AI. Kita hanya minta gambar yang <strong>baik dan lucu</strong> ya. 🛡️' },
      { tipe: 'teks', mood: 'bangga', judul: 'Ayo Buat Mantramu!',
        teks: 'Sekarang giliranmu merangkai mantra ajaib sendiri! Pilih bahan-bahannya, lalu minta Mama/Papa mencobanya di alat AI. Selamat menyihir! 🌟' },
    ],
    kuis: [
      { soal: 'Kalimat yang kita berikan ke AI untuk membuat gambar disebut...',
        pilihan: ['Prompt (mantra)', 'Lagu', 'Kata sandi', 'Judul buku'], benar: 0,
        penjelasan: 'Perintah untuk AI disebut prompt — kita menyebutnya mantra ajaib.' },
      { soal: 'Mantra mana yang akan membuat gambar paling bagus dan sesuai?',
        pilihan: ['"gambar"', '"kucing"', '"kucing oranye lucu pakai topi di taman bunga"', '"hewan"'], benar: 2,
        penjelasan: 'Makin jelas dan lengkap mantranya, makin bagus hasil gambar AI.' },
      { soal: 'Supaya AI membuat VIDEO (gambar bergerak), kita tambahkan kata tentang...',
        pilihan: ['Gerakan, misalnya melompat', 'Harga', 'Nama kita', 'Tanggal lahir'], benar: 0,
        penjelasan: 'Kata gerakan membuat AI mengubah gambar menjadi video.' },
      { soal: 'Saat mau memakai alat AI, sebaiknya kita...',
        pilihan: ['Diam-diam sendiri', 'Ditemani Mama atau Papa', 'Memberi tahu alamat rumah', 'Tengah malam'], benar: 1,
        penjelasan: 'Alat AI sebaiknya dibuka bersama orang dewasa supaya aman.' },
      { soal: 'Kalau hasil gambar AI belum sesuai keinginan, sebaiknya kita...',
        pilihan: ['Menyerah', 'Memperbaiki mantra lalu coba lagi', 'Marah pada AI', 'Menghapus semuanya'], benar: 1,
        penjelasan: 'Perbaiki mantra agar lebih jelas, lalu coba lagi — itu hal biasa!' },
    ],
    aktivitas: {
      tipe: 'mantra',
      judul: 'Pembuat Mantra Ajaib 🪄',
      petunjuk: 'Pilih satu kartu di tiap baris. Lihat mantramu terbentuk, lalu Salin atau Bagikan ke Mama/Papa untuk dicoba di alat AI!',
      pola: '{0} {1} di {2}, gaya {3}',
      bagian: [
        { label: 'Tokoh', pilihan: ['anak kucing oranye', 'naga kecil biru', 'putri peri', 'robot lucu', 'anak panda'] },
        { label: 'Sedang', pilihan: ['memakai topi pesta', 'terbang tinggi', 'makan es krim', 'bermain bola', 'membaca buku'] },
        { label: 'Tempat', pilihan: ['taman bunga', 'kota awan', 'tepi pantai', 'hutan ajaib', 'luar angkasa'] },
        { label: 'Gaya', pilihan: ['kartun lucu', 'warna pastel', 'cerah ceria', 'seperti dongeng'] },
      ],
      gerakan: ['(diam saja)', 'lalu melompat-lompat', 'lalu menari riang', 'kamera bergerak pelan'],
    },
  },

  {
    id: 9,
    judul: 'Pameran Karya',
    emoji: '🎉',
    tag: 'Pamerkan hasilmu',
    warna: '#ff9fc4',
    lencana: { ikon: '🏆', nama: 'Desainer Hebat' },
    langkah: [
      { tipe: 'teks', mood: 'semangat', judul: 'Selamat Datang di Pameran! 🎉',
        teks: 'Kamu sudah belajar <strong>banyak sekali</strong>: warna, bentuk, garis, pola, karakter, latar, cerita, sampai <strong>sihir AI</strong>! Hari ini saatnya <strong>memamerkan</strong> karya terbaikmu!' },
      { tipe: 'bentuk', mood: 'bangga', judul: 'Lihat Semua yang Kamu Kuasai!',
        teks: 'Dari bentuk sederhana ini, kamu kini bisa membuat apa saja. Hebat! ⭐',
        bentuk: [
          { bentuk: 'lingkaran', warna: '#4fc3f7', nama: 'Warna' },
          { bentuk: 'segitiga', warna: '#ffb74d', nama: 'Bentuk' },
          { bentuk: 'bintang', warna: '#ff7aa8', nama: 'Karya' },
        ] },
      { tipe: 'teks', mood: 'bangga', judul: 'Mahakarya Terakhir',
        teks: 'Untuk lulus jadi <strong>Desainer Hebat</strong>, buatlah satu karya bebas — gabungkan semua yang kamu pelajari. Bebas berkreasi! 🌈' },
    ],
    kuis: [
      { soal: 'Selama kursus, kamu sudah belajar warna, bentuk, garis, pola, karakter, latar, dan...',
        pilihan: ['Cerita', 'Memasak', 'Berenang', 'Menyanyi'], benar: 0,
        penjelasan: 'Pertemuan 7 mengajarkan cara bercerita lewat gambar.' },
      { soal: 'Kalau gambarmu belum sempurna, sebaiknya kamu...',
        pilihan: ['Menyerah', 'Terus berlatih', 'Berhenti menggambar', 'Marah'], benar: 1,
        penjelasan: 'Desainer hebat terus berlatih dan tidak takut salah.' },
      { soal: 'Karya yang paling keren biasanya menggabungkan...',
        pilihan: ['Semua yang sudah dipelajari', 'Satu warna saja', 'Tidak ada bentuk', 'Hanya garis lurus'], benar: 0,
        penjelasan: 'Menggabungkan warna, bentuk, garis, karakter, dan cerita membuat karya kaya.' },
      { soal: 'Sikap seorang desainer hebat adalah...',
        pilihan: ['Berani mencoba dan berkreasi', 'Takut salah', 'Meniru terus', 'Cepat menyerah'], benar: 0,
        penjelasan: 'Keberanian mencoba ide baru adalah kunci jadi desainer hebat.' },
    ],
    aktivitas: { tipe: 'menggambar', judul: 'Mahakarya Bebasmu! 🏆',
      petunjuk: 'Inilah panggungmu! Gambar apa pun yang kamu banggakan dengan semua ilmu desainmu. Tunjukkan pada dunia!',
      palet: ['#ff7aa8', '#7ec8f3', '#5fcf80', '#ffd93b', '#ff9f43', '#a96fd0', '#4a4a6a', '#ffffff'] },
  },
];

export function cariPertemuan(id) {
  return pertemuan.find((p) => p.id === Number(id));
}

export const totalPertemuan = pertemuan.length;

// =========================================================
// Panduan tiap pertemuan: tujuan belajar (ditampilkan di awal)
// dan ringkasan (ditampilkan di akhir). Membuat terasa
// berkurikulum seperti kursus profesional.
// =========================================================
const panduan = {
  1: { tujuan: ['Mengenal 3 warna utama: merah, kuning, biru', 'Mencampur warna menjadi warna baru', 'Membedakan warna hangat dan sejuk'],
       ringkasan: ['Warna utama: merah, kuning, biru', 'Biru + kuning = hijau', 'Warna hangat ceria, warna sejuk menenangkan'] },
  2: { tujuan: ['Mengenal bentuk dasar: lingkaran, persegi, segitiga', 'Menggabungkan bentuk menjadi gambar', 'Memecah benda jadi bentuk sederhana'],
       ringkasan: ['Bentuk dasar ada di mana-mana', 'Rumah = persegi + segitiga', 'Gambar rumit dimulai dari bentuk sederhana'] },
  3: { tujuan: ['Mengenal jenis garis: lurus, lengkung, zigzag', 'Memahami bahwa garis punya "rasa"', 'Memilih garis sesuai gambar'],
       ringkasan: ['Lurus = tenang, lengkung = lembut, zigzag = seru', 'Garis tebal terasa kuat dan berani', 'Gambar dibangun dari garis'] },
  4: { tujuan: ['Memahami arti pola (motif berulang)', 'Membuat pola dari bentuk sederhana', 'Menjaga jarak agar pola rapi'],
       ringkasan: ['Pola = motif yang berulang teratur', 'Jarak yang sama membuat pola rapi', 'Pola ada di batik, baju, kertas kado'] },
  5: { tujuan: ['Membuat karakter dari bentuk sederhana', 'Membuat karakter terlihat hidup', 'Berani berkreasi dengan warna'],
       ringkasan: ['Wajah dimulai dari lingkaran', 'Mata besar & senyum bikin karakter hidup', 'Karaktermu bebas berwarna apa saja'] },
  6: { tujuan: ['Memahami fungsi latar (background)', 'Menggambar kesan jauh dan dekat', 'Memakai warna untuk suasana'],
       ringkasan: ['Latar menunjukkan tempat & suasana', 'Jauh = kecil di atas, dekat = besar di bawah', 'Warna gelap = malam, terang = siang'] },
  7: { tujuan: ['Memahami cerita: awal, tengah, akhir', 'Menggabungkan karakter dan latar', 'Bercerita lewat satu gambar'],
       ringkasan: ['Cerita punya awal, tengah, akhir', 'Karakter + latar = gambar bercerita', 'Gambar sederhana pun bisa berkesan'] },
  8: { tujuan: ['Mengenal AI sebagai alat bantu kreatif', 'Menulis "mantra" (prompt) yang jelas', 'Memakai AI dengan aman'],
       ringkasan: ['Prompt = mantra untuk AI', 'Resep: siapa + sedang apa + di mana + gaya', 'Pakai AI selalu bersama orang dewasa'] },
  9: { tujuan: ['Menggabungkan semua yang dipelajari', 'Membuat karya bebas yang dibanggakan', 'Berani memamerkan karya'],
       ringkasan: ['Kamu menguasai warna, bentuk, garis, pola, karakter, latar, cerita & AI', 'Desainer hebat berani mencoba', 'Karyamu layak dipamerkan!'] },
};

export function panduanPertemuan(id) {
  return panduan[Number(id)] || null;
}
